AZURE_OPENAI_API_KEY : '' 
AZURE_OPENAI_ENDPOINT : ''
AZURE_OPENAI_VERSION : '2024-08-01-preview' 
AZURE_GPT4O_MODEL : 'gpt-4o'
AZURE_OPENAI_EMBEDDINGS_MODEL: ''
LANGCHAIN_ENDPOINT : 'https://api.smith.langchain.com'
LANGCHAIN_API_KEY : ''
LANGCHAIN_PROJECT : ''
TAVILY_API_KEY : 'tvly-'
AI_SEARCH_KEY: ''
AI_SEARCH_ENDPOINT: ''